printWidth: 80
semi: false
singleQuote: false
trailingComma: "none"
bracketSpacing: true
proseWrap: "always"

plugins:
  - prettier-plugin-svelte

overrides:
  - files: "*.svelte"
    options:
      parser: svelte
