# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coordinator.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "coordinator.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x63oordinator.proto\x12\x0b\x63oordinator\x1a\x1bgoogle/protobuf/empty.proto"$\n\x11HeartbeatResponse\x12\x0f\n\x07version\x18\x01 \x01(\t"4\n\x15RegisterWorkerRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2\xa4\x01\n\x0b\x43oordinator\x12\x45\n\tHeartbeat\x12\x16.google.protobuf.Empty\x1a\x1e.coordinator.HeartbeatResponse"\x00\x12N\n\x0eRegisterWorker\x12".coordinator.RegisterWorkerRequest\x1a\x16.google.protobuf.Empty"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "coordinator_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_HEARTBEATRESPONSE"]._serialized_start = 63
    _globals["_HEARTBEATRESPONSE"]._serialized_end = 99
    _globals["_REGISTERWORKERREQUEST"]._serialized_start = 101
    _globals["_REGISTERWORKERREQUEST"]._serialized_end = 153
    _globals["_COORDINATOR"]._serialized_start = 156
    _globals["_COORDINATOR"]._serialized_end = 320
# @@protoc_insertion_point(module_scope)
