[package]
name = "doculens"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
clap = "4.5.23"

# gRPC
tonic = "0.12.3"
prost = "0.13.4"

# Tracing
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

# Utils
dotenv = "0.15.0"

[build-dependencies]
tonic-build = "0.12.3"
