#![allow(clippy::all)]
#![allow(unused_qualifications)]

//! This module includes types and submodules of the coordinator server
//! generated by Tonic from the coordinator.proto file.

tonic::include_proto!("coordinator");
