name: Quality Check Extractor

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "extractor/**"

  push:
    branches:
      - main
    paths:
      - "extractor/**"

jobs:
  ci:
    name: Check Code Quality & Run Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: extractor

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Run Formatter
        run: poetry run black --check .

      - name: Run Tests
        run: poetry run pytest
