name: Quality Check Server

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "server/**"

  push:
    branches:
      - main
    paths:
      - "server/**"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  ci:
    name: Test & Check Code Quality
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Protobuf Compiler
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y protobuf-compiler libprotobuf-dev

      - name: Setup Local Environment
        run: cd .. && make setup_server

      - name: Run Formatter
        run: cargo fmt -- --check

      - name: Run Linter
        run: cargo clippy -- -D warnings

      - name: Run Tests
        run: cargo test -- --test-threads 1
