name: Quality Check Web

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "web/**"

  push:
    branches:
      - main
    paths:
      - "web/**"

jobs:
  ci:
    name: Check Code Quality
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Linting & Formatting Check
        run: npm run lint
