name: Quality Check Web

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "web/**"

  push:
    branches:
      - main
    paths:
      - "web/**"

jobs:
  ci:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd web
          npm install

      - name: Run Linting & Formatting Check
        run: |
          cd web
          npm run lint
